### ISSUE TITLE
Server crash when spawning a Wither

### ISSUE THREAD

**Issue by ACGaming** [Turkey2349/WitherCrumbs#3]
All clients in vicinity disconnect when the last head is placed.
We're using the latest versions of both Headcrumbs and Withercrumbs.
1.7.10 by the way.

[Client crash excerpt](http://pastebin.com/RKCLcDkU)
[Server crash excerpt](http://pastebin.com/2FscahyS)

**Comment by TheTurkeyDev** [comment]
Your crash reports are not really pointing to anything specific in either mod. The logs just contain a lot of information about bad network connections

**Comment by ACGaming** [comment]
Well, how could a Wither break a network connection? Never saw a "Broken pipe" error before.

**Comment by TheTurkeyDev** [comment]
Broken Pipes occur when a client closes it's connection, but the server isn't notified of this and thus when it tried to send data to the client is incurs the broken pipe exception. As far as I know the wither can't cause this problem and has to do with something else on the client causing it to crash or close it's connections with the server.

**Comment by ACGaming** [comment]
Alright! I think that helps quite a bit. :)
We have about 330 mods installed. I have to spot the mods with Wither-changing mechanics which could be the culprit(s).
Thank you nonetheless!
