### ISSUE TITLE
"The Beginning."-achievement are not getting triggered with WitherCrumbs installed

### ISSUE THREAD

**Issue by GirafiStudios** [Turkey2349/WitherCrumbs#4]
Killing the wither with WitherCrumbs installed makes "The Beginning"-achievement not trigger.
I tested this in both a singleplayer world and on a server with only WitherCrumbs and HeadCrumbs installed.

Minecraft version: 1.10.2
Minecraft Forge version: 12.18.3.2221
HeadCrumbs version: 2.0.1
WitherCrumbs version: 0.9

**Comment by TheTurkeyDev** [comment]
I can look into adding this

**Comment by Tiredman72** [comment]
Has this been fixed? for Sky Factory 3?

**Comment by TheTurkeyDev** [comment]
It's been fixed, but I don't think SF3 is receiving any more updates
